export const delegationCardAbi = [
  {
    type: "function",
    name: "approveSpend",
    inputs: [{ name: "spendId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cards",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "authorizedAgent", type: "address", internalType: "address" },
      { name: "totalBudget", type: "uint256", internalType: "uint256" },
      { name: "spentAmount", type: "uint256", internalType: "uint256" },
      { name: "autoApproveLimit", type: "uint256", internalType: "uint256" },
      { name: "expiryTimestamp", type: "uint256", internalType: "uint256" },
      { name: "isActive", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createCard",
    inputs: [
      { name: "budget", type: "uint256", internalType: "uint256" },
      { name: "autoApproveLimit", type: "uint256", internalType: "uint256" },
      { name: "expiryDays", type: "uint256", internalType: "uint256" },
      { name: "authorizedAgent", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "idrxToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCard",
    inputs: [{ name: "cardId", type: "uint256", internalType: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        internalType: "struct DelegationCard.Card",
        components: [
          { name: "owner", type: "address", internalType: "address" },
          { name: "authorizedAgent", type: "address", internalType: "address" },
          { name: "totalBudget", type: "uint256", internalType: "uint256" },
          { name: "spentAmount", type: "uint256", internalType: "uint256" },
          { name: "autoApproveLimit", type: "uint256", internalType: "uint256" },
          { name: "expiryTimestamp", type: "uint256", internalType: "uint256" },
          { name: "isActive", type: "bool", internalType: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOwnerCards",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256[]", internalType: "uint256[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ownerCards",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingSpends",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "cardId", type: "uint256", internalType: "uint256" },
      { name: "merchant", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "description", type: "string", internalType: "string" },
      { name: "isApproved", type: "bool", internalType: "bool" },
      { name: "isRejected", type: "bool", internalType: "bool" },
      { name: "isExecuted", type: "bool", internalType: "bool" },
      { name: "createdAt", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "rejectSpend",
    inputs: [{ name: "spendId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeCard",
    inputs: [{ name: "cardId", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "spend",
    inputs: [
      { name: "cardId", type: "uint256", internalType: "uint256" },
      { name: "merchant", type: "address", internalType: "address payable" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "description", type: "string", internalType: "string" },
    ],
    outputs: [
      { name: "autoApproved", type: "bool", internalType: "bool" },
      { name: "pendingSpendId", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "CardCreated",
    inputs: [
      { name: "cardId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "owner", type: "address", indexed: true, internalType: "address" },
      { name: "budget", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CardRevoked",
    inputs: [{ name: "cardId", type: "uint256", indexed: true, internalType: "uint256" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "SpendApproved",
    inputs: [{ name: "spendId", type: "uint256", indexed: true, internalType: "uint256" }],
    anonymous: false,
  },
  {
    type: "event",
    name: "SpendExecuted",
    inputs: [
      { name: "cardId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "merchant", type: "address", indexed: true, internalType: "address" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SpendPending",
    inputs: [
      { name: "spendId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "cardId", type: "uint256", indexed: true, internalType: "uint256" },
      { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SpendRejected",
    inputs: [{ name: "spendId", type: "uint256", indexed: true, internalType: "uint256" }],
    anonymous: false,
  },
] as const;
